# Notebook 2 - Vector and Matrix Operations (Answers only)
### Name: Angel Arwen E. Reyes
### Section: S07

In [7]:
import numpy as np

**Practice!** Select the number 14 from the matrix `X`.

In [8]:
X = np.array([[ 2,  4,  6],
              [ 8, 10, 12],
              [14, 16, 18]])

# Write your code here
X[2, 0]

14

**Practice!** Select the third row from the matrix `Y` (the one with 1s).

In [9]:
Y = np.array([[0, 0, 0, 0],
              [0, 0, 0, 0],
              [1, 1, 1, 1],
              [0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]])

# Write your code here
Y[2, :]

array([1, 1, 1, 1])

**Practice!** Select the first three columns from matrix `C`, but exclude the last row which only contains zeroes.

In [10]:
C = np.array([[ 1,  3,  5,  7,  9],
              [11, 13, 15, 17, 19],
              [21, 23, 25, 27, 29],
              [ 0,  0,  0,  0,  0]])

# Write your code here
C[0:3, :]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

**Practice!** Reshape the vector `v` to come up with a matrix where the first (leftmost) column contains only 1s.

In [11]:
v = np.array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

# Write your code here
v = v.reshape((2,6))
v[:, 0] = 1

print(v)

[[1 0 0 0 1 0]
 [1 0 1 0 0 0]]


**Practice!** Complete the definition for the matrix `beta` such that the result of adding `alpha` and `beta` is a matrix containing only zeros.

In [12]:
alpha = np.array([[3, 2, 1],
                  [6, 5, 4],
                  [9, 8, 7]])

beta = np.array([[-3,-2,-1],
                 [-6,-5,-4],
                 [-9,-8,-7]])

alpha + beta

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Practice!** If you take a row vector and perform matrix multiplication with its transpose, you will get the sum of the squares of each element in the original vector. Verify this by performing this operation on the given vector `v`. This should result into $1^2 + 2^2 + 3^2 + 4^2 = 30$.


In [15]:
v = np.array([[1, 2, 3, 4]])

# Write your code here
y = v.T
np.dot(v,y)

array([[30]])

**Practice!** Create a function that returns `True` if the integer is even or `False` if the integer is odd. Vectorize this function so that it could be applied to the vector `list`.


In [17]:
list = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

def is_even(n):
    # Write your code here
    if n % 2 == 0: 
        return True
    return False

# Vectorize the function
is_even_vectorized = np.vectorize(is_even)

# Apply it to the list vector
is_even_vectorized(list)

array([[False,  True, False,  True, False,  True, False,  True, False,
         True]])

**Practice!** Write code that adds a row to the matrix `grid` containing the highest value in each column. For example, given the matrix:
\begin{equation*}
\begin{bmatrix}
2 & 3 & 1 & 6 \\
4 & 9 & 2 & 7 \\
3 & 3 & 5 & 1
\end{bmatrix}
\end{equation*}
The resulting matrix should be:
\begin{equation*}
\begin{bmatrix}
2 & 3 & 1 & 6 \\
4 & 9 & 2 & 7 \\
3 & 3 & 5 & 1 \\
4 & 9 & 5 & 7
\end{bmatrix}
\end{equation*}

**Note**: `max` returns a 1-dimensional vector, so might need to reshape it to a 2-dimensional row vector before you can concatenate it to the original matrix.

In [19]:
grid = np.array([[2, 3, 1, 6],
                 [4, 9, 2, 7],
                 [3, 3, 5, 1]])

# Write your code here
mx = np.max(grid, axis=0)
mx = mx.reshape((1,4))

c = np.concatenate((grid,mx))
print(c)

[[2 3 1 6]
 [4 9 2 7]
 [3 3 5 1]
 [4 9 5 7]]
